# Generated by Django 4.0.4 on 2023-08-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolgroup',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='schoolgroup',
            unique_together={('school_year', 'group_number')},
        ),
    ]
