FROM python:3.9.17-alpine

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


RUN apk update && apk upgrade \
    && apk add --no-cache \
    git \
    gcc \
    musl-dev \
    libxslt-dev \
    libxml2-dev \
    libffi-dev \
    && apk add --virtual build-deps python3-dev \
    && apk add --no-cache mariadb-dev

RUN pip install --upgrade pip

COPY . .

RUN pip install -r requirements.txt

RUN apk del build-deps

RUN mkdir ../school-control-logs

CMD["sh", "entrypoint.sh"]