# Generated by Django 4.0.4 on 2023-07-12 05:15

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('program_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero del programa')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la carrera')),
                ('number_semesters', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de semestres')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
