# Generated by Django 4.0.4 on 2023-08-14 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional_careers', '0001_initial'),
        ('school_subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsubject',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_subject_carrer', to='professional_careers.professionalcareer'),
        ),
    ]
