# Generated by Django 4.0.4 on 2023-08-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Foto del usuario'),
        ),
    ]
